'use strict';
import './css/poppins.css';
import './css/reset.css';
import './css/styles.css';
import { F, HtmlElement } from './js/Functions.js';
import { NavigationBar } from './js/NavigationBar/NavigationBar.js';
// import { clickEvents, keydownEvents } from './js/globalEvents.js';

import { greeting } from './greeting.js';
import odinImage from './img/odin-lined.png';

// import { showSlides } from './js/slideshowW3.js';

import { Slideshow } from './js/Slideshow/Slideshow.js';
import { ImageArray } from './js/Slideshow/ImageArray.js';
import { Dropdown } from './js/Dropdown/Dropdown.js';
import { Settings } from './js/Dropdown/Settings.js';

// dev
function dev() {
  console.log(greeting);
  F.addOutlineToAllElements(false);
  document.addEventListener('click', (e) => {
    console.log(e.target);
  });
}

document.addEventListener('DOMContentLoaded', () => {
  dev();

  console.log('DOM fully loaded and parsed.');

  const html = document.querySelector('html');
  const baseFontSize = Number(
    window.getComputedStyle(html).fontSize.match(/\d+/g),
  );
  const content = document.getElementById('content');

  const navBtns = ['Home', 'About', 'Login', 'Sign Up', 'Whatever'];
  const navigationBar = new NavigationBar(5, navBtns, true, baseFontSize);
  content.appendChild(navigationBar);
  content.style.marginTop = `${5}rem`; // offset the rest of the content by the height of the navbar

  // newdropdown button
  // const ddcont = F.htmlElement();
  // ddcont.style.width = '7rem';
  // ddcont.style.height = '7rem';
  // ddcont.style.position = 'relative';
  // const seti = new Settings(ddcont);
  // const dd = new Dropdown(seti);
  // ddcont.appendChild(dd);
  // content.appendChild(ddcont);

  // create slideshow
  const ssImages = new ImageArray;
  const slideshow = new Slideshow(ssImages, '600px', '400px', true, 5);
  content.appendChild(slideshow);


  // new F.EventHandler(clickEvents, 'click');
  // new F.EventHandler(keydownEvents, 'keydown');


});


// import ss1 from "./img/odin-lined.png";
// const ss1img = document.createElement("img");
// image.src =

// Todo
//  - Fix menu alignment bug in Dropdown.js. Check NavigationBar for solution

// - To commit
//  - Convert SlideshowImages.js to a class
//  - Refactor & convert Slideshow.js to a class
//  - Take an image array generated by SlideshowImages.js as a parameter to make it easier to generate multiple slideshows
